### PR TITLE
script to generate Jackson and Fischer example dataset

### PR DESCRIPTION
**Pull request by JanaFischer**

### CODE REVIEW

**Comment by jwindhager** [comment]
Just stumbled upon this, looks good! :-) would just recommend to use a platform-independent way of unzipping, if possible

**Comment by JanaFischer** [comment]
Good point regarding the platform-independent unzipping but the standard R unzip function does not work in this case because the zip files are too big. Are you aware of a different way to unzip platform independently?

**Comment by jwindhager** [comment]
As discussed in the zoom meeting: probably not important to do this

In case you want to, though, you could try something like

    unzip(..., unzip=getOption("unzip"))

This should use platform-specific tools, which, on most unix systems, should be set to the `unzip` command you are using already.

**Comment by ndamond** [comment]
The `unzip(..., unzip=getOption("unzip"))` doesn't seem to work with files > 4Gb, while the `system2("unzip", ...)` does, but maybe I missed something.
`getOption("unzip")` returns "internal"

**Comment by jwindhager** [comment]
> The `unzip(..., unzip=getOption("unzip"))` doesn't seem to work with files > 4Gb, while the `system2("unzip", ...)` does, but maybe I missed something.
> `getOption("unzip")` returns "internal"

Looks like on Unix systems, `getOption("unzip")` defaults to the `R_UNZIPCMD` environment variable, which is usually set in `etc/Renviron`. It seems that [older versions of RStudio Cloud forget to set that environment variable](https://community.rstudio.com/t/rstudio-cloud-does-not-set-r-unzipcmd/9524) and default to `"internal"`.

In any case, as said above, I don't think this is important. If you would like to make the script "platform-independent", you could also just introduce a config variable at the beginning of the script that holds the value for the `unzip` parameter of R's `unzip`.

**Comment by ndamond** [comment]
Looking good!

**Pull request merged**
