### PR TITLE
Zanotelli dataset

### PR DESCRIPTION
**Pull request by ndamond**
Adding dataset from Zanotelli et al (2016) Mol Syst Biol

### CODE REVIEW

**Review by ndamond — COMMENTED** [review]
ok

**Review by nilseling — APPROVED** [review]
This looks excellent! Have a look at the few points we discussed: 1. storing the neighbouring expression levels in `altExp(sce, "counts_neighbours")` and 2. checking again what the bit encoding for Vitos images is.

**Comment by ndamond** [comment]
Added a new issue for the `altExp` point (https://github.com/BodenmillerGroup/imcdatasets/issues/11#issue-870006846). It will be fixed later on as this requires to re-upload the dataset to ExperimentHub.
The scaling on Vito's images looks good:
```
> images <- ZanotelliSpheroids2020Data(data_type = "images")
> images[[1]]
Image 
  colorMode    : Grayscale 
  storage.mode : double 
  dim          : 321 318 51 
  frames.total : 51 
  frames.render: 51 

imageData(object)[1:5,1:6,1]
     [,1] [,2] [,3] [,4] [,5] [,6]
[1,]    0    2    9    2    0    1
[2,]    0    0    3    0    0    1
[3,]    1    0    0    5    1    3
[4,]    2    0    0    3    2    1
[5,]    1    2    2    0    0    1
```

**Comment by nilseling** [comment]
Very nice!

**Pull request merged**
